-- Import ATC data using the CSV files generated by sql-to-csv
--
-- Before running this, you should :
--   1. Generate CSV files using the cli:
--      infomed-html-parser sql-to-csv ClasseATC_data.sql -o classe_atc.csv
--      infomed-html-parser sql-to-csv VUClassesATC_data.sql -o cis_atc.csv
--
--   2. Run the Kysely migration in infomedicament:
--      npm run db:migrate:latest
--
-- Usage:
--   Connect to the database interactively and run the \copy commands manually,
--   replacing the file paths with absolute paths to the CSV files.
--
--   NOTE: \copy does NOT support psql variable interpolation (:'var' syntax).
--   This is a documented psql limitation, not a bug.
--   See: https://www.postgresql.org/docs/current/app-psql.html
--
-- Example:
--   psql $APP_DB_URL
--   -- Then paste the commands below, replacing paths:
--
--   TRUNCATE TABLE cis_atc CASCADE;
--   TRUNCATE TABLE atc CASCADE;
--   \copy atc(code_terme, code_terme_pere, code, label_court, label_long, label_anglais, label_recherche, num_ordre_edit, date_creation, date_modification, date_inactivation, source_ref, remarque) FROM '/absolute/path/to/classe_atc.csv' WITH (FORMAT csv, HEADER true, NULL '');
--   \copy cis_atc(code_cis, code_terme_atc, est_valide, est_certain, commentaire, date_creation, date_modification, code_modif) FROM '/absolute/path/to/cis_atc.csv' WITH (FORMAT csv, HEADER true, NULL '');

-- Empty existing tables
TRUNCATE TABLE cis_atc CASCADE;
TRUNCATE TABLE atc CASCADE;

-- Load ATC
-- Replace the path below with the absolute path to classe_atc.csv
\copy atc(code_terme, code_terme_pere, code, label_court, label_long, label_anglais, label_recherche, num_ordre_edit, date_creation, date_modification, date_inactivation, source_ref, remarque) FROM '/path/to/classe_atc.csv' WITH (FORMAT csv, HEADER true, NULL '');

-- Load CIS-ATC
-- Replace the path below with the absolute path to cis_atc.csv
\copy cis_atc(code_cis, code_terme_atc, est_valide, est_certain, commentaire, date_creation, date_modification, code_modif) FROM '/path/to/cis_atc.csv' WITH (FORMAT csv, HEADER true, NULL '');

-- Check
SELECT 'atc' as table_name, COUNT(*) as row_count FROM atc
UNION ALL
SELECT 'cis_atc', COUNT(*) FROM cis_atc;
